# Development-specific configuration
lis:
  instruments:
    - name: OrthoVision
      port: 9001
      enabled: true  # Enable for development testing
      keepAliveIntervalMinutes: 30  # Keep-alive every 30 minutes for development
      driverClassName: com.lis.astm.server.driver.impl.OrthoVisionDriver
    
  
  # Development messaging configuration (enabled for integration testing)
  messaging:
    enabled: true  # Enable RabbitMQ for development
    retry:
      batch-size: 10
      max-attempts: 5
      collision-delay-minutes: 30
      connection-delay-minutes: 60
      schedule-interval-ms: 600000  # 10 minutes
    
# Custom properties for application
log_path: D:/astm-interface-services-data/logs

# Development Database Configuration
spring:
  datasource:
    url: jdbc:sqlserver://${DB_HOST:dev-sql.internal}:1433;databaseName=ASTM_Interface_Dev;trustServerCertificate=true
    username: ${DB_USERNAME:astm_dev_user}
    password: ${DB_PASSWORD:dev_password}
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    hikari:
      maximum-pool-size: 10
      connection-timeout: 30000
      idle-timeout: 300000
  
  # Enable scheduling for retry processing
  task:
    scheduling:
      pool:
        size: 3

  # Development RabbitMQ Configuration
  rabbitmq:
    host: dev-rabbitmq.internal  # Development RabbitMQ server
    port: 5672
    username: ${RABBITMQ_USERNAME:dev_user}
    password: ${RABBITMQ_PASSWORD:dev_password}


# Development Server Configuration
server:
  port: 8080