# Production-specific configuration
lis:
  instruments:
    - name: OrthoVision
      port: 9001
      enabled: true
      maxConnections: 10  # Higher connection pool for production
      connectionTimeoutSeconds: 60  # Longer timeout for production stability
      keepAliveIntervalMinutes: 60  # Keep-alive every hour for production VISION® systems
    
  
  # Production messaging configuration (fully enabled)
  messaging:
    enabled: true  # Enable RabbitMQ for production
    retry:
      batch-size: 20
      max-attempts: 10
      collision-delay-minutes: 30
      connection-delay-minutes: 60
      schedule-interval-ms: 300000  # 5 minutes for production

# Logging configuration  
log_path: D:/astm-interface-services-data/logs

# Production Database Configuration
spring:
  datasource:
    url: jdbc:sqlserver://${DB_HOST:prod-sql.internal}:1433;databaseName=ASTM_Interface_Prod;encrypt=true;trustServerCertificate=false
    username: ${DB_USERNAME}  # Must be provided via environment variables
    password: ${DB_PASSWORD}  # Must be provided via environment variables
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    hikari:
      maximum-pool-size: 20
      connection-timeout: 30000
      idle-timeout: 300000
      max-lifetime: 900000
      leak-detection-threshold: 60000
  
  # Enable scheduling for retry processing
  task:
    scheduling:
      pool:
        size: 5

  # Production RabbitMQ Configuration
  rabbitmq:
    host: ${RABBITMQ_HOST:prod-rabbitmq.internal}  # Production RabbitMQ cluster
    port: ${RABBITMQ_PORT:5672}
    username: ${RABBITMQ_USERNAME}  # Must be provided via environment variables
    password: ${RABBITMQ_PASSWORD}  # Must be provided via environment variables
    connection-timeout: 60s  # Longer timeout for production
    requested-heartbeat: 30s  # More frequent heartbeat for production monitoring


# Production Server Configuration
server:
  port: ${SERVER_PORT:8080}
  # Production security headers
  servlet:
    context-path: /astm-interface